version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883" # mqtt
      - "9001:9001" # websocket
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  influxdb:
    image: influxdb
    container_name: influxdb
    environment:
      INFLUXDB_META_DIR: /var/lib/influxdb/meta
      INFLUXDB_DATA_DIR: /var/lib/influxdb/data
      INFLUXDB_DATA_WAL_DIR: /var/lib/influxdb/wal
    # ports:
    #   - "8086:8086"
    volumes:
      - ./influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./influxdb/meta:/var/lib/influxdb/meta
      - ./influxdb/data:/var/lib/influxdb/data
      - ./influxdb/wal:/var/lib/influxdb/wal

  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb

  kapacitor:
    image: kapacitor
    container_name: kapacitor
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    # ports:
    #   - "9092:9092"
    depends_on:
      - influxdb

  chronograf:
    image: chronograf
    container_name: chronograf
    volumes:
      - ./chronograf/data:/var/lib/chronograf
    environment:
      - HOST_PAGE_DISABLED=true
    ports:
      - "8888:8888"
    depends_on:
      - kapacitor
      - influxdb
      - telegraf

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080

  webapp-flask:
    build: ./webapp-flask
    image: webapp-flask
    container_name: webapp-flask
    command:
      [
        "./wait-for-it.sh",
        "postgres:5432",
        "--",
        "uwsgi",
        "--yaml",
        "/app/uwsgi.yml",
      ]
    environment:
      EMAIL_VERIFICATION: ${EMAIL_VERIFICATION}
      MAIL_SERVER:
      MAIL_PORT:
      MAIL_USERNAME:
      MAIL_PASSWORD:
      MAIL_DEFAULT_SENDER:
      JWT_SECRET_KEY:
    volumes:
      - ./webapp-flask/app:/app
    ports:
      - 80:80
    depends_on:
      - postgres
